services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      APP_ENV: ${APP_ENV:-dev}
      MESSENGER_TRANSPORT_DSN: amqp://${RMQ_USER:-guest}:${RMQ_PASS:-guest}@rabbitmq:${RMQ_PORT:-5672}/${RMQ_VHOST:-%2f}/messages

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    ports:
      - "${RMQ_PORT:-5672}:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASS:-guest}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5